http:
  address: "0.0.0.0"
  port: 8888

tunnel_to:
  proto: "http"
  address: "ssl-webclient.roboime.com"
  port: 8888

zmq_conf:
  address: "0.0.0.0"
  push_port: 66654
  pull_port: 66655

# by default debugging is off
debug: false

# wether this server is also an ssl tunneler to itself
self_tunnel: false

# enable live reload? useful for development
livereload: false

# enable console? (for use with intel backend only)
console: false

# official ssl parameters
# commonly used ports are listed respectively
# to use them customize your development config

vision:
  address: "224.5.23.2"
  port: 10002
  #port: 11002

referee:
  address: "224.5.23.1"
  port: 10003
  #port: 11003
